apiVersion: v1
kind: Pod
metadata:
  name: non-root-demo
spec:
  containers:
  # ❌ Fails with CreateContainerConfigError (root image + runAsNonRoot)
  - name: ubuntu-root
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    securityContext:
      runAsNonRoot: true

  # ❌ Fails with CrashLoopBackOff (non-root user tries privileged port)
  - name: nginx-nonroot
    image: nginx
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    ports:
      - containerPort: 80   # binding to 80 fails for non-root

  # ✅ Succeeds (image defines USER nobody)
  - name: alpine-nonroot
    image: alpine:3.19
    command: ["sleep", "3600"]
    securityContext:
      runAsNonRoot: true

  # ✅ Succeeds (explicit non-root UID)
  - name: forced-nonroot
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000