apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  # Single container pod, useful for debugging or simple tasks
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
    # In production, prefer Deployments for self-healing