apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: dev   
  labels:
    type: frontend
spec:
  initContainers:
  - name: print
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["date; echo Hello"]
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80