apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'echo Hello > /data/host.txt && sleep 3600']
    volumeMounts:
    - name: host-volume
      mountPath: /data
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp/data  # Path on host node
      type: DirectoryOrCreate