apiVersion: v1
kind: Pod
metadata:
  name: nfs-example
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'ls /nfs && sleep 3600']
    volumeMounts:
    - name: nfs-volume
      mountPath: /nfs
  volumes:
  - name: nfs-volume
    nfs:
      server: 10.0.0.5
      path: /exported/data
