apiVersion: v1
kind: Pod
metadata:
  name: pvc-using-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'echo Data > /data/file.txt && sleep 3600']
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-example
