apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: "standard"  # Optionally specify your StorageClass
# PVC requests dynamic provisioning from a StorageClass in most clusters.