apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:                                              
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort

---
# Instructions to deploy Jenkins and access it
# kubectl apply -f jenkins-deploy.yaml
# kubectl get all -n jenkins
# Access Jenkins at: http://<NodeIP>:31000
# Initial Admin Password:
# kubectl exec -n jenkins -it <jenkins-pod-name> -- cat /var/jenkins_home/secrets/initialAdminPassword
# Example:
# kubectl exec -n jenkins -it jenkins-deployment-5c9f7d6b7b-abcde -- cat /var/jenkins_home/secrets/initialAdminPassword
# Remember to replace <jenkins-pod-name> with the actual pod name obtained from 'kubectl get pods -n jenkins'
# https://github.com/vamshii7/100-Days-Of-DevOps/blob/main/Day68_Set_Up_Jenkins_Server.md