apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
    variables_order = "EGPCS"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
type: Opaque
stringData:
  password: j@rv!s
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
stringData:
  username: vamshi
  password: j@rv!s
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
type: Opaque
stringData:
  database: mydb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp
  template:
    metadata:
      labels:
        app: lamp
    spec:
      containers:
      - name: httpd-php-container
        image: webdevops/php-apache:alpine-3-php7
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-pass
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-db-url
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: password
          - name: MYSQL_HOST
            value: mysql-service
        volumeMounts:
          - name: php-config
            mountPath: /opt/docker/etc/php/php.ini
            subPath: php.ini
      - name: mysql-container
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-pass
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-db-url
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: password
      volumes:
      - name: php-config
        configMap:
          name: php-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: lamp
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: NodePort
  selector:
    app: lamp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
---
# PHP Config index.php file to test LAMP stack and DB connection

# <?php
# // Fetch MySQL connection details from environment variables
# $dbname = getenv('MYSQL_DATABASE');
# $dbuser = getenv('MYSQL_USER');
# $dbpass = getenv('MYSQL_PASSWORD');
# $dbhost = getenv('MYSQL_HOST');

# // Create connection
# $conn = mysqli_connect($dbhost, $dbuser, $dbpass, $dbname);

# // Check connection
# if (!$conn) {
#     die("Connection failed: " . mysqli_connect_error());
# }

# // Run a simple query to verify DB access
# $test_query = "SHOW TABLES";
# $result = mysqli_query($conn, $test_query);

# if (!$result) {
#     echo "Connected to MySQL but could not query database '$dbname'.<br>";
#     echo "Error: " . mysqli_error($conn);
# } else {
#     echo "Connected successfully";
# }

# // Close connection
# mysqli_close($conn);
# ?>
# Save this file as index.php and place it in the web root directory of the PHP container to test the LAMP stack.
# kbectl cp /tmp/index.php lamp-wp-<pod-name>:/app -c httpd-php-container
# https://github.com/vamshii7/100-Days-Of-DevOps/blob/main/Configure_LAMP_Stack_Application.md