apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      # Run on all nodes in KinD (control-plane included)
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.2
        imagePullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 25m
            memory: 40Mi
          limits:
            cpu: 100m
            memory: 100Mi

        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true

        # Fluent Bit minimal config baked inside container:
        # - Tail container logs
        # - Auto-detect format
        # - Output to stdout
        command: ["/fluent-bit/bin/fluent-bit"]
        args:
          - -i
          - tail
          - -p
          - path=/var/log/containers/*.log
          - -p
          - multiline.parser=docker
          - -o
          - stdout

      terminationGracePeriodSeconds: 10

      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: containers
        hostPath:
          path: /var/lib/docker/containers