# StorageClass for Azure Disk CSI (managed disks)
# Requires: Azure Disk CSI driver installed in the cluster (disk.csi.azure.com)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-sc
provisioner: disk.csi.azure.com
reclaimPolicy: Delete            # Delete the cloud disk when PVC is deleted (choose Retain for critical data)
volumeBindingMode: WaitForFirstConsumer  # Ensures volume is provisioned in the node's zone
parameters:
  skuName: Premium_LRS           # Disk SKU: Standard_LRS / Premium_LRS
---
# PVC that requests dynamically provisioned Azure Disk using the above StorageClass
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-sc
  resources:
    requests:
      storage: 8Gi
