apiVersion: v1
kind: Pod
metadata:
  name: ambassador-demo
spec:
  containers:
  - name: app
    image: curlimages/curl
    command: ["sleep", "3600"]
  - name: ambassador
    image: envoyproxy/envoy:v1.29.0
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: envoy-config
        mountPath: /etc/envoy
  volumes:
  - name: envoy-config
    configMap:
      name: envoy-config
