apiVersion: v1
kind: Pod
metadata:
  name: log-collector-demo
spec:
  containers:
  - name: web
    image: nginx
    volumeMounts:
      - name: logs
        mountPath: /var/log/nginx
  - name: log-shipper
    image: fluent/fluent-bit
    args: ["-i", "tail", "-p", "path=/var/log/nginx/access.log", "-o", "stdout"]
    volumeMounts:
      - name: logs
        mountPath: /var/log/nginx
  volumes:
  - name: logs
    emptyDir: {}
