apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  containers:
  - name: app
    image: nginx:latest
    ports:
      - containerPort: 80
  - name: sidecar-logger
    image: busybox
    command: ["/bin/sh", "-c", "tail -n+1 -F /var/log/nginx/access.log"]
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx
  volumes:
  - name: shared-logs
    emptyDir: {}
