apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=           # 'admin' base64 encoded (replace in prod)
  password: cGFzc3dvcmQ=       # 'password' base64 encoded (replace in prod)
# Use external secret managers in production; rotate keys regularly.