resources:
  repositories:
    - repository: terraformRepo
      type: github
      name: vamshii7/Kubernetes-Hands-On
      ref: main
      endpoint: github.com_vamshii7

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  displayName: "🚀 Deploy nginx on AKS"
  jobs:
  - job: DeployNginx
    displayName: "Deploy nginx on AKS"
    steps:
      - checkout: terraformRepo
      - script: |
          echo "Files pulled from Repo:"
          ls -lR deployments/
        displayName: "List checked out files"

      - task: KubectlInstaller@0
        inputs:
          kubectlVersion: 'latest'

      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'KubernetesConnection'
          manifests: 'deployments/Deployment.yaml'